version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - mongo:/etc/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: local123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: local123
      ME_CONFIG_MONGODB_URL: mongodb://root:local123@mongo:27017/
